jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ou qualquer versão do Python que você queira usar

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Gerar executável
        run: |
          pyinstaller --onefile --windowed \
            --add-data "assets/tiro.wav:assets" \
            --add-data "assets/nave.png:assets" \
            jogo.py
