name: Build macOS Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ajuste para a versão que você quiser

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar dependências do sistema
        run: |
          brew install pyinstaller

      - name: Gerar executável
        run: |
          pyinstaller --onefile --windowed \
            --add-data "assets/tiro.wav:assets" \
            --add-data "assets/nave.png:assets" \
            jogo.py

      - name: Fazer upload do executável
        uses: actions/upload-artifact@v2
        with:
          name: jogo-mac
          path: dist/jogo
